* ProbABEL
  ProbABEL is a tool for genome-wide association analysis of imputed
  genetic data. It is part of the GenABEL Suite of tools developed by
  within the GenABEL Project.
** IMPORTANT NOTICE
   Early 2018, PolyOmica, the main sponsor of the GenABEL project announced that it would discontinue its support.
   As PolyOmica was our only sponsor, we regretfully have to announce the likely discontinuation of the GenABEL
   Project in its current form, unless a new sponsor steps up or someone takes over maintenance and further
   development of (some of) the tools.
** Installation
   Please see the =INSTALL= file in the =doc= directory for more
   information on how to install ProbABEL.
** Licence
   ProbABEL is licensed under the GNU Public Licence v2 or later.

   #+begin_example
   This program is free software; you can redistribute it and/or
   modify it under the terms of the GNU General Public License
   as published by the Free Software Foundation; either version 2
   of the License, or (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
   #+end_example
