name: build
run-name: ProbABEL build and tests
on: [push]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt install -y build-essential
      - run: autoreconf -i
      - run: ./configure
      - run: make
      - run: make check
